// Code generated by mockery 2.9.0. DO NOT EDIT.

package service

import mock "github.com/stretchr/testify/mock"

// mockTools is an autogenerated mock type for the tools type
type mockTools struct {
	mock.Mock
}

// hashPassword provides a mock function with given fields: password
func (_m *mockTools) hashPassword(password string) (string, error) {
	ret := _m.Called(password)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
